### ISSUE TITLE
Fix installation directory path

### ISSUE THREAD

**Issue by ghost** [Arction/lcu-tutorial-installation-00#1]
C:\Program Files (x86)\Arction\LightningChart Ultimate SDK v.8\LibNET4. text should have double slashes and be inline-code.

**Comment by Nikolsi** [comment]
Thanks! I have changed the path to be in a code block.
If people wants to copy that path to navigate to the directory, double slashes are not the best way to show the path because it will show the error alert "Windows can't find.... Check the spelling and try again"
